components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: API for retrieving pool swim lane schedules.
  title: Toronto Swim Lane Tracker API
  version: 1.0.0
openapi: 3.1.0
paths:
  /openapi.yaml:
    get:
      description: Get the OpenAPI schema in YAML format
      operationId: serve_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          description: Successful Response
      summary: Serve Openapi Yaml
  /pools:
    get:
      description: 'Endpoint to get a list of pools with lane swims today at or after
        the current time.

        Supports filtering by start_date and end_date with hour, minute, and second
        precision,

        and a simplified response format.'
      operationId: pools_pools_get
      parameters:
      - description: Filter pools starting from this datetime (YYYY-MM-DDTHH:MM:SS)
        in: query
        name: start_date
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Filter pools starting from this datetime (YYYY-MM-DDTHH:MM:SS)
          title: Start Date
      - description: Filter pools ending before this datetime (YYYY-MM-DDTHH:MM:SS)
        in: query
        name: end_date
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Filter pools ending before this datetime (YYYY-MM-DDTHH:MM:SS)
          title: End Date
      - description: Return a simplified response with pool name and times
        in: query
        name: simple
        required: false
        schema:
          anyOf:
          - type: boolean
          - type: 'null'
          default: false
          description: Return a simplified response with pool name and times
          title: Simple
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  additionalProperties: true
                  type: object
                title: Response Pools Pools Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Pools
